### ISSUE TITLE
Prometheus plugin Unable to use error

### ISSUE THREAD

**Issue by exceedzhang** [raiffeisenbankinternational/jmeter-prometheus-plugin#1]
After I downloaded the source code and compiled it successfully, I put all the jars in the JMeter / lib / ext directory. Add Prometheus status export Listener and the following error occurs:

Uncaught Exception java.lang.NoClassDefFoundError: org/xnio/ChannelListener. See log file for details.

I wonder if the other undertow jar package hasn't been added?

**Comment by rpofuk** [comment]
Thank you reporting issue. Can you please give more insights for your environent:

i.e: Java version, JMeter version, Running in container?

Thank you!

**Comment by exceedzhang** [comment]
> Thank you reporting issue.
> 
> Can you please give more insights for your environment?
> 
> i.e: Java version, JMeter version, Running in container?
> 
> Thank you!
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Apache Maven 3.5.0
JMeter 5.0 r1840935

**Comment by yangangtest** [comment]
2019-12-24 19:48:52,296 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: org/xnio/ChannelListener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_191]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at com.rbinternational.monitoring.jmeter.PrometheusStatusExporter.testStarted(PrometheusStatusExporter.java:50) ~[jmeter-prometheus-plugin-0.0.1-SNAPSHOT.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: org.xnio.ChannelListener
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 15 more

**Comment by rpofuk** [comment]
Fixed! 
Updated readme to include more information about how to install plugin.
